# this configuration file maps sensors to fans
# TODO:
# pwm upper, lower bound
# triggers for modes?
# default polling time is once per second
# default controlDelay is 5 seconds
# default averaging time is 5 seconds
settings:
  controlDelay: 2s
  averagintTime: 2s
  pollingTime: 5s
sensors:
- name: cpu
  device: /sys/class/hwmon/hwmon0/temp1
  divisor: 1000
  crit: 90
- name: mainboard
  device: /sys/class/hwmon/hwmon2/device/temp1
  crit: 40
  beep: 1
- name: southbridge
  device: /sys/class/hwmon/hwmon2/device/temp2
- name: temp3
  device: /sys/class/hwmon/hwmon2/device/temp3
  crit: 80
  max: 60
  crit_beep: 1
- name: hdd1
  device: /dev/sda
  smart: True
  tempId: 194
  divisor: 1
  min: 30
  max: 40
- name: hdd2
  device: /dev/sdb
  smart: True
  min: 30
  max: 40
- name: hdd3
  device: /dev/sdc
  smart: True
  min: 30
  max: 40
- name: hdd4
  device: /dev/sdd
  smart: True
  min: 30
  max: 40
fans:
- name: cpuFan
  device: /sys/class/hwmon/hwmon2/device/pwm1
  pwm: True
- name: front
  device: /sys/class/hwmon/hwmon2/device/pwm2
  pwm: True
- name: top
  device: /sys/class/hwmon/hwmon2/device/pwm3
  pwm: True
controllers:
- name: topController
  inputs:
  - name: cpu
    weight: 5
  outputs:
  - name: cpuFan
    curve:
    - temp: 50
      pwm: 70
    - temp: 70
      pwm: 120
    - temp: 86
      pwm: 255
  - name: top
  
- name: frontController
  inputs:
  - name: hdd1
    weight: 5
  - name: hdd2
    weight: 5
  - name: hdd3
    weight: 5
  - name: hdd4
  outputs:
    - name: front
      curve:
      - temp: 20
        pwm: 80
      - temp: 30
        pwm: 120
      - temp: 40
        pwm: 255
#- fans:
#  - name: top
#    device: /sys/class/hwmon2/device/pwm2
#    enable: 2
#    auto_channels_temp: 3
#    auto_point1_pwm: 50


